name: Wrangler Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy Go Worker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Compile Go to WebAssembly
      run: GOOS=js GOARCH=wasm go build -o main.wasm

    - name: Set up Wrangler
      run: npm install -g wrangler

    - name: Deploy to Cloudflare Workers
      run: wrangler publish
